[13.0] Move On-Hand status out of purchase order line
OCA/ddmrp pull request #157
Opened 2021-07-21 07:45 UTC by TDu

In the purchase order form view, the on hand status is visible in the
ordered lines tree view.
This information slows down the load of every large purchase order when
this information is not always usefull.

To improve on this. This change removes the on hand status from the
purchase order form.
And adds a smart button on the from to visualize this information.

2021-07-23 08:47 UTC, mmequignon approved these changes

2021-07-26 12:28 UTC, sebalix approved these changes

2021-09-02 13:25 UTC, LoisRForgeFlow commented
Maybe a silly question but... how come this field `execution_priority_level` can slow the loading? it is an stored field, I would understand if it was a computed one, but it is not obvious to me on an stored one.

Thanks for clarifying!

2021-09-02 13:26 UTC, LoisRForgeFlow requested changes
to mark that I did a question.

2021-09-06 11:41 UTC, TDu commented
> Maybe a silly question but... how come this field `execution_priority_level` can slow the loading? it is an stored field, I would understand if it was a computed one, but it is not obvious to me on an stored one.
> 
> Thanks for clarifying!

Hi Lois, thanks for your review, the field that is slowing the load is `on_hand_percent`, the other field `execution_priority_level` was invisible and use to format the value of `on_hand_percent` that is why it was removed as well.

2021-10-04 14:11 UTC, LoisRForgeFlow commented
> > Maybe a silly question but... how come this field `execution_priority_level` can slow the loading? it is an stored field, I would understand if it was a computed one, but it is not obvious to me on an stored one.
> > Thanks for clarifying!
> 
> Hi Lois, thanks for your review, the field that is slowing the load is `on_hand_percent`, the other field `execution_priority_level` was invisible and use to format the value of `on_hand_percent` that is why it was removed as well.

Same goes for `on_hand_percent`, it is not a computed field, how does it slow loading?

Sorry for my slow replies here...

2021-10-14 06:30 UTC, TDu commented
@LoisRForgeFlow You are correct. Actually there is no computed field on ddmrp `purchase.order.line` changes.
Still this PR seems to have help the customer with slow performance on large purchase order. But I can understand that it would be a shame to remove the buffer information from this view.

2021-11-03 11:53 UTC, LoisRForgeFlow commented
Yes, I'm quite doubtful of this move because I think they provide a value. Maybe we can move this change to optional module and control its installation/uninstallation from the ddmrp setting panel?

2022-01-17 13:28 UTC, TDu commented
@LoisRForgeFlow  For v14 I took your suggestion and move this change to an optional module. https://github.com/OCA/ddmrp/pull/194

2022-06-26 12:36 UTC, closed without merging