[14][FWD] [FIX] Disable unarchiving buffer on product activation
OCA/ddmrp pull request #187
Opened 2021-12-08 07:01 UTC by TDu

Forward port of https://github.com/OCA/ddmrp/pull/180

2021-12-08 09:42 UTC, sebalix approved these changes

2021-12-13 08:38 UTC, simahawk requested changes

2021-12-13 08:38 UTC, simahawk commented on ddmrp/models/product_product.py
> +            buffers = self.env["stock.buffer"].search([("product_id", "in", self.ids)])
```suggestion
            buffers = self.env["stock.buffer"].sudo().search([("product_id", "in", self.ids)])
```

2022-01-25 12:28 UTC, LoisRForgeFlow commented
@TDu thanks, can you remove the last 2 commits and keep only the 1st one?

2022-01-27 11:00 UTC, TDu commented
@LoisRForgeFlow  Done

2022-02-03 12:56 UTC, LoisRForgeFlow approved these changes

2022-02-03 12:56 UTC, LoisRForgeFlow commented
/ocabot merge patch

2022-02-03 13:03 UTC, merged