[14.0] ddmrp_adjustment: keep RO access for 'Inventory / User' group
OCA/ddmrp pull request #402
Opened 2024-02-23 15:26 UTC by sebalix

As `Inventory / Users` have a read only access to buffers, should not we keep a RO access as well on `demand.adjustment`?

Currently a stock user is unable to open a buffer if `ddmrp_adjustment` is installed without being part of the `DDMRP / Stock Buffer Maintainer` group (which gives create/write access to buffers, not always what we want).

I cannot say about other data models, I let you check this (I revert the changes done [here](https://github.com/OCA/ddmrp/commit/53ffd4e4f3342d10e65a06df4aba2717762e44b0) on RO access rights) and will update my PR accordingly if needed.

Another question: is `DDMRP / DDMRP Manager` required to create adjustments (I'm not familiar with this feature, just wondering)?

cc @BernatPForgeFlow @LoisRForgeFlow

2024-03-05 09:48 UTC, LoisRForgeFlow requested changes
Thanks for pointing to the issue, you are correct. I would do a copule of extra tweaks though.

- could you change the groups of menu_ddmrp_adjustment_sheet_wizard to be group_stock_buffer_maintainer?
- Adjust security accordingle as mentioned below

2024-03-05 09:48 UTC, LoisRForgeFlow commented on ddmrp_adjustment/security/ir.model.access.csv
> -ddmrp_adjustment_access_sheet_user,ddmrp.adjustment.sheet.user,model_ddmrp_adjustment_sheet,ddmrp.group_stock_buffer_maintainer,1,0,0,0
This line is a wizard, I don't thing it doesn't even have sense to have readonly access to a wizar. You can just remove the line.

2024-03-05 09:48 UTC, LoisRForgeFlow commented on ddmrp_adjustment/security/ir.model.access.csv
> -ddmrp_adjustment_access_sheet_line_user,ddmrp.adjustment.sheet.line.user,model_ddmrp_adjustment_sheet_line,ddmrp.group_stock_buffer_maintainer,1,0,0,0
Same here. This line is a wizard, I don't thing it doesn't even have sense to have readonly access to a wizar. You can just remove the line.

2024-03-05 09:48 UTC, LoisRForgeFlow commented on ddmrp_adjustment/security/ir.model.access.csv
>  ddmrp_adjustment_access_sheet_manager,ddmrp.adjustment.sheet.manager,model_ddmrp_adjustment_sheet,ddmrp.group_ddmrp_manager,1,1,1,1
Allow to use this wizard to buffer maintainers (group_stock_buffer_maintainer)

2024-03-05 09:48 UTC, LoisRForgeFlow commented on ddmrp_adjustment/security/ir.model.access.csv
>  ddmrp_adjustment_access_sheet_line_manager,ddmrp.adjustment.sheet.line.manager,model_ddmrp_adjustment_sheet_line,ddmrp.group_ddmrp_manager,1,1,1,1
I would allow to use this wizard to buffer maintainers (group_stock_buffer_maintainer)

2024-03-12 13:21 UTC, JuMiSanAr commented
Hello @LoisRForgeFlow ,

I've applied your comments in the permissions file, let me know if that looks ok now.

2024-03-12 13:56 UTC, LoisRForgeFlow reviewed
Hi @JuMiSanAr 

Thanks for following up. There is one more detail missing, you still need to change the permissions of this menu item so it is accesible to buffer maintainers:

![image](https://github.com/OCA/ddmrp/assets/23449160/ef84f942-3d0c-4a27-a9c4-a3836494d6a8)

2024-03-13 12:02 UTC, JuMiSanAr commented
> Hi @JuMiSanAr
> 
> Thanks for following up. There is one more detail missing, you still need to change the permissions of this menu item so it is accesible to buffer maintainers:
> 
> ![image](https://private-user-images.githubusercontent.com/23449160/312103338-ef84f942-3d0c-4a27-a9c4-a3836494d6a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzE0NzAsIm5iZiI6MTcxMDMzMTE3MCwicGF0aCI6Ii8yMzQ0OTE2MC8zMTIxMDMzMzgtZWY4NGY5NDItM2QwYy00YTI3LWE5YzQtYTM4MzY0OTRkNmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExNTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYzEzZjBlMzFhMzBjOWUyNDdjMjkzOTQ0ZTE4ZWI1MzhlMzQ5Y2FhMDMxMTgzZDU1NjA3YjYwODVmZTgzODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zZn9qVPlkiVTT2GjHVP1H59zS7Af41I7OLVPRj6hJ7c)

@LoisRForgeFlow 

Thanks, also updated!
If it ok like this, or ddmrp managers should also have acces to it?

2024-03-15 07:19 UTC, simahawk commented
@LoisRForgeFlow gentle ping :)

2024-03-22 09:44 UTC, LoisRForgeFlow requested changes
The demo user (buffer maintainer) get's an error creating DAFs:

![image](https://github.com/OCA/ddmrp/assets/23449160/916806cd-6797-4b5c-870d-cadadd50da39)

Could you fix that?

Thanks!

2024-03-22 12:50 UTC, JuMiSanAr commented
> The demo user (buffer maintainer) get's an error creating DAFs:
> 
> ![image](https://private-user-images.githubusercontent.com/23449160/315962374-916806cd-6797-4b5c-870d-cadadd50da39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTIwMzgsIm5iZiI6MTcxMTExMTczOCwicGF0aCI6Ii8yMzQ0OTE2MC8zMTU5NjIzNzQtOTE2ODA2Y2QtNjc5Ny00YjVjLTg3MGQtY2FkYWRkNTBkYTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEyNDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxOTZmMDUwNjU3Y2Q1MDBmOTZmY2I3Mzg3OGY2ZmIyZDc3NjA1OTJmOTI3YmFkYjk4YTNkODU0OTYxNDk1YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W-muPPgrmMCgTr2kpdRxgVqucik__yn4fpN9f9vIe5I)
> 
> Could you fix that?
> 
> Thanks!

@LoisRForgeFlow I've now given `ddmrp.adjustment` and `ddmrp.adjustment.demand` access to stock buffer maintainers, that should fix it.

2024-03-22 14:08 UTC, LoisRForgeFlow approved these changes
All good now. Thanks!

/ocabot merge minor

2024-03-22 14:12 UTC, merged