[13.0] Add option to limit replenishment to free quantity
OCA/ddmrp pull request #92
Opened 2020-12-09 16:03 UTC by guewen

This new feature targets buffers of type 'distributed'.

* Store the source location where the replenishment of a buffer should
  occur.
* The source location is taken from the default first route, so we
  assume the default route is a replenishment, otherwise the computation
  is skipped.
* When `stock_buffer_route` is installed, the route configured on the
  buffer is used to find the replenishment source location.
* A computed field shows the free quantity in the replenishment source
  location.
* When a buffer has no quantity in the replenishment source location, a
  new warning is displayed in the tree view.
* A new option on the buffer profile limits the quantity that can be
  replenished in the procurement wizard to the actual free quantity in
  the replenishment source location. The quantity we can procure for
  this profile will be min(recommended quantity, free quantity).

This is a huge win to avoid backorders for transfers created for
replenishments: we create transfers only for the quantity we have, and
if we do not have this quantity in practice, it reveals a stock issue.

2020-12-10 09:43 UTC, sebalix approved these changes

2020-12-10 09:55 UTC, TDu approved these changes

2020-12-16 14:30 UTC, jbaudoux requested changes
Fails with "Quantity must be positive." when the buffer is configured in auto-procure but the free qty in source is 0 as it prevents to create a procurement of quantity 0. This error prevent also the refresh of the buffer (as the refresh trigger the auto-procure that fails).

2020-12-17 09:22 UTC, guewen commented
@jbaudoux fixed in my last commit

2020-12-17 09:48 UTC, simahawk approved these changes
LG

2020-12-17 11:53 UTC, jbaudoux approved these changes

2020-12-17 13:03 UTC, LoisRForgeFlow approved these changes
Tested, works smoothly :+1:

2020-12-17 13:03 UTC, LoisRForgeFlow commented
/ocabot merge minor

2020-12-17 16:31 UTC, merged